install: make get-deps libsdl2* libglew* libglut* libglew-dev:i386 libsndfile-dev cmake

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  - cmake . && make