#install: make get-deps libsdl2* libglew* libglut* libglew-dev:i386 libsndfile-dev cmake
dist: trusty

addons:
  apt:
    packages:
    - git
    - cmake
    - dos2unix
    - libosmesa6-dev
    - libegl1-mesa-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libsdl2-mixer-dev
    - libsndfile-dev
    - libalut0
    - libglew-dev
    - freeglut3-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - cmake . && make