#install: make get-deps libsdl2* libglew* libglut* libglew-dev:i386 libsndfile-dev cmake
dist: trusty

addons:
  apt:
    packages:
    - git
    - cmake
    - dos2unix
    - libosmesa6-dev
    - libegl1-mesa-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libsdl2-mixer-dev
    - libsndfile-dev
    - libalut0
    - libglew-dev:i386
  artifacts:
    bucket: glew
    s3_region: "us-east-1"
    paths:
    - $(ls *.zip *.tgz | tr "\n" ":")
    - $(find doc -type f | tr "\n" ":")

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - cmake . && make